name: Update Frozen API Responses

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Reset head to main
        run: |
          git fetch
          git checkout main
          git reset --hard origin/main

      - name: Run freeze
        run: |
          yarn freeze | tee freeze.log
          if grep -q "Unexpected" freeze.log; then
            echo "::warning title=Unexpected response encountered::One or more API responses did not match the expected format. This may be due to a change in the API or a rate limit being reached."
          fi

      - name: Check for changes
        id: git-check
        run: |
          if git diff-index --quiet HEAD --; then
            echo "no changes"
            echo "status=no-changes" >> $GITHUB_ENV
          else
            echo "changes"
            echo "status=changes" >> $GITHUB_ENV
          fi

      - name: Commit and push if changes
        if: steps.git-check.outputs.status == 'changes'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am 'chore: auto-update frozen API responses'
          git push
