name: Update Frozen API Responses

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Reset head to main
        run: |
          git fetch
          git checkout main
          git reset --hard origin/main

      - name: Run freeze
        run: yarn freeze

      - uses: stefanzweifel/git-auto-commit-action@v5
